# Generated by Django 3.1.3 on 2021-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('raca', models.CharField(max_length=50)),
                ('vida', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('poder', models.CharField(max_length=50)),
                ('dificuldade', models.IntegerField()),
            ],
        ),
    ]
